### PR TITLE
Updating structure and adding pages

### PR DESCRIPTION
**Pull request by nsewnath**

### CODE REVIEW

**Comment by nsewnath** [comment]
Not sure what these checks mean

**Comment by meghalithic** [comment]
@jdeck88 could you help?

**Comment by nsewnath** [comment]
Checking the config file again:

- Noticing that about.md is missing which could be one of the problems. I'm not sure where https://futreswebsite.netlify.com/about/ is pointing to. 
- I'm also not sure where https://futreswebsite.netlify.com/projects/ would be pointing to in the config file, because a projects page doesn't exist anymore in the update.

**Comment by meghalithic** [comment]
it seems the read more is called as "about_us" in the config file rather than "about"

"projects" is "community projects"

**Pull request closed without merging**
